### ISSUE TITLE
re applying amp to war 5.0.d

### ISSUE THREAD

**Issue by digcat** [ecm4u/businessdocumentmodel#1]
hi guys
thought id report this, not sure if you know.  tried compiling for 5.0.d, which seems to package up the amp fine.  But when I apply_amps.sh I get 

Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.simontuffs.onejar.Boot.run(Boot.java:287)
        at com.simontuffs.onejar.Boot.main(Boot.java:137)
Caused by: org.alfresco.error.AlfrescoRuntimeException: 04240000 The version string '1.0-SNAPSHOT' is invalid.
        at org.alfresco.util.VersionNumber.<init>(VersionNumber.java:80)
        at org.alfresco.repo.module.ModuleDetailsImpl.<init>(ModuleDetailsImpl.java:137)
        at org.alfresco.repo.module.tool.ModuleDetailsHelper.createModuleDetailsFromPropertiesStream(ModuleDetailsHelper.java:53)
        at org.alfresco.repo.module.tool.ModuleDetailsHelper.createModuleDetailsFromPropertyLocation(ModuleDetailsHelper.java:83)
        at org.alfresco.repo.module.tool.ModuleManagementTool.installModule(ModuleManagementTool.java:227)
        at org.alfresco.repo.module.tool.ModuleManagementTool.installModules(ModuleManagementTool.java:170)
        at org.alfresco.repo.module.tool.ModuleManagementTool.installModules(ModuleManagementTool.java:153)
        at org.alfresco.repo.module.tool.ModuleManagementTool.main(ModuleManagementTool.java:867)
        ... 6 more

**Comment by ghost** [comment]
Thank you, I will test and fix this.

**Comment by ghost** [comment]
I can't reproduce this. Alfresco 5.0d starts fine with the module deployed.

```
2016-05-24 15:48:03,858  INFO  [repo.module.ModuleServiceImpl] [localhost-startStop-1] Starting module 'businessdocumentmodel' version 1.0-SNAPSHOT.   
```

I don't recognize the `com.simontuffs.onejar` package in your stacktrace. What do you use to run Alfresco?

**Comment by ghost** [comment]
No error when using `./bin/apply-amps.sh`:

```
Module 'businessdocumentmodel' installed in '/home/lutz/devenv/src/alf/50d/alfresco-5.0.d/tomcat/webapps/alfresco.war'
   -    Title:        businessdocumentmodel Repository AMP project
   -    Version:      1.0-SNAPSHOT
   -    Install Date: Tue May 24 15:46:07 CEST 2016
   -    Description:   Manages the lifecycle of the businessdocumentmodel Repository AMP (Alfresco Module Package)

```

**Comment by ghost** [comment]
I've changed the project to build a JAR, not an AMP. This makes deployment much easier: https://docs.alfresco.com/5.1/concepts/dev-extensions-packaging-techniques-jar-files.html
